### DISCUSSION TITLE
Can a Catalog object point at a config file?

### DISCUSSION THREAD

**Discussion by Pellifer** [eclipse-symphony/symphony#121] [Q&A]
In this example below we show how a Catalog can point at a other Catalog as part of its definition. Can a Catalog also point directly at files, like a config file in the below example?  @Haishi2016 

```
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: app-config
spec:  
  siteId: hq
  type: config
  name: app-config
  parentName: global-config
  metadata:
    asset: use-case
  properties:
    line: <line-config>     
```
