### ISSUE TITLE
Catalog Creation fails with error "spec.catalogType: Required value"

### ISSUE THREAD

**Issue by roopavidhya** [eclipse-symphony/symphony#335]
I tried installing the symphony OSS agent and creating a catalog. 

`PS C:\Users\groopa\source\repos\Edge-ConfigurationManager\symphony-poc> kubectl apply -f .\connectivity.yml`

Catalog creation failed with error - `The Catalog "connectivity" is invalid: spec.catalogType: Required value`

Catalog - 
```
apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: connectivity
spec:  
  catalogType: config
  properties:
    ...
```

This was the case with agent versions `0.48.20` and `0.48.25`
