### ISSUE TITLE
When component properties is null, symphony will send a lot of job

### ISSUE THREAD

**Issue by yanjiaxin534** [eclipse-symphony/symphony#593]
apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: remote-target
  namespace: default
spec:
  components:
  - name: remote-agent
    type: helm.v3
  reconciliationPolicy:
    interval: 10m
  displayName: remote-target
  scope: default
  topologies:
  - bindings:
    - config:
        ApplyScript: mock-apply.sh
        GetScript: mock-get.sh
        RemoveScript: mock-remove.sh
        ScriptFolder: ./script
        StagingFolder: ./script
      provider: providers.target.script
      role: script
    - provider: providers.target.helm
      role: helm.v3

**Comment by msftcoderdjw** [comment]
Related to mutation webhook.
Can easily repro this by repeatedly apply below yaml, properties: null (you will see the generation always bump up)
```yaml
apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: remote-solution
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: remote-solution-v-v1
spec:
  rootResource: remote-solution
  components:
  - name: remote-agent
    type: remote-agent
    properties: null
```
