### ISSUE TITLE
Defining cpu using millicores seems doesn't work

### ISSUE THREAD

**Issue by LeiQL** [eclipse-symphony/symphony#70]
````
apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: sample-prometheus-server
spec:  
  metadata:
    deployment.replicas: "#1"
    service.ports: "[{\"name\":\"port9090\",\"port\": 9090}]"
    service.type: "LoadBalancer"
  components:
  - name: sample-prometheus-server
    type: container
    properties:
      container.ports: "[{\"containerPort\":9090,\"protocol\":\"TCP\"}]"
      container.imagePullPolicy: "Always"
      container.resources: "{\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}}"        
      container.image: "prom/prometheus"
````

Issue: 100m will be translated to 100 cpu in existing k8s.provider.
Doc: https://github.com/Azure/symphony/blob/d4172fbb2166af16962562dafd919928a8c01bdc/docs/symphony-book/quick_start/deploy_prometheus_k8s.md
